name: Atualizador de Listas

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # Opcional: Adicione um agendamento para atualizar sozinho a cada 12 horas
  # schedule:
  #   - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Requests
        run: pip install requests

      - name: Executar Script
        run: python verificar_listas.py

      - name: Salvar Arquivos
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/*.m3u
          # O comando abaixo evita que o erro "nothing to commit" pare o processo
          git commit -m "Listas atualizadas via Paix√£oFlix" || exit 0
          git push
